### ISSUE TITLE
Remove NN

### ISSUE THREAD

**Issue by boshek** [boshek/limnotools#2]
change nn in higher functions from desired length of output to match the length of the input. The length of the output does not appear after a length of approximately 300. This would making any of these higher level functions throw an error is nn is lower than 300. 
![nn_loop](https://cloud.githubusercontent.com/assets/18472598/22555643/2dc81a46-e919-11e6-9c70-6ea0100bf0ff.png)

**Comment by boshek** [comment]
Setting 
```r
nn=length(z)
```
rather than 
```r
nn=800
```
changes the results of by_s_m() and by_s_m3() such that it no longer passes it tests that compare it to the original fortran code. The differences are small. However, it does result in enough of a difference that the tests fail.

**Comment by DougCollinge** [comment]
I don't think that failing the tests when you change nn is any sort of problem. Sure, it is bound to get slightly different results. Give some thought to what you think success is for this new code and we'll build appropriate tests.
