### ISSUE TITLE
Segment vs min_depth

### ISSUE THREAD

**Issue by boshek** [boshek/limnotools#4]
Encountering some instances where the depth of the shallowest segment is shallower that the specified mean depth meaning the algorithm is extending beyond the specified depth range. Will add data to make this clear.

**Comment by boshek** [comment]
The number of segments is quite resistant to changes in mininum depth. Early spring profiles where the stratification has not significantly been established show the greatest variation in nseg.
![image](https://cloud.githubusercontent.com/assets/18472598/22705453/63c814f6-ed20-11e6-9fc7-b27c070850e1.png)

**Comment by boshek** [comment]
The number of segments is quite resistant to changes in mininum depth. Early spring and late fall profiles where the stratification has not significantly been established show the greatest variation in nseg: 
![image](https://cloud.githubusercontent.com/assets/18472598/22708966/126eaf72-ed2d-11e6-9648-ed9120e12892.png)

**Comment by DougCollinge** [comment]
I don't think I understand this chart. I think I need to look over the data for a while.

**Comment by boshek** [comment]
So this is some external data of thousands of profiles. But what I did loop over z0 (min_depth) from 0.1 to 3.5 in increments of 0.1 just to see what effect it had on the number of segments (nseg) found by the sm algorithm. Starting depth is an underemphasized part of the original algorithm. More on that to come.
